# bridge_2.yaml
from_domain: 2
to_domain: 13
topics:
  state:
    type: nuri_msgs/msg/NuriBotState
    remap: /robot2/state
  location:
    type: nuri_msgs/msg/NuriBotLocation
    remap: /robot2/location
  tracked_pose:
    type: geometry_msgs/msg/PoseStamped
    remap: /robot2/tracked_pose
  map:
    type: nav_msgs/msg/OccupancyGrid
    remap: /robot2/map
  emergency_msg:
    from_domain: 13
    to_domain: 2
    type: std_msgs/msg/String
    remap: /robot2/emergency_msg
  status_list:
    from_domain: 13
    to_domain: 2
    type: std_msgs/msg/String
    remap: /robot2/status_list
  patrol:
    from_domain: 13
    to_domain: 2
    type: std_msgs/msg/Bool
    remap: /robot2/patrol
  /robot2/goal_pose:
    from_domain: 13
    to_domain: 2
    type: geometry_msgs/msg/PoseStamped
    remap: /goal_pose