from enum import Enum

class Opcode(Enum):
    CLIENT_HELLO = 0x00
    RESIDENT_LIST = 0x01
    SEND_RESIDENT_INFO = 0x02
    REQUEST_RESIDENT_INFO = 0x03
    REQUEST_DISCHARGE = 0x04
    UPDATE_RESIDENT_INFO = 0x05
    DELETE_RESIDENT = 0x06

    LOG_CATEGORY = 0x20

    DETECTION = 0x30
    REQUEST_VIDEO = 0x31